export type AuditEventType =
  | 'RMA_STARTED'
  | 'OWNERSHIP_VALIDATED'
  | 'WARRANTY_CHECKED'
  | 'PLAYBOOK_STEP_COMPLETED'
  | 'EVIDENCE_UPLOADED'
  | 'CUSTOMER_OPTED_OUT'
  | 'TERMS_ACCEPTED'
  | 'RULE_DECISION'
  | 'LABEL_OPTIONS_SHOWN'
  | 'LABEL_PURCHASED'
  | 'TRACKING_RECORDED'
  | 'HUBSPOT_TICKET_CREATED'
  | 'HUBSPOT_TICKET_UPDATED'
  | 'ADMIN_OVERRIDE'
  | 'STORAGE_CLEANUP';

export type AuditActorType =
  | 'CUSTOMER'
  | 'RULE_ENGINE'
  | 'AI'
  | 'AGENT'
  | 'SYSTEM';

