export type RmaStatus =
  | 'DRAFT'
  | 'STARTED'
  | 'TROUBLESHOOTING_IN_PROGRESS'
  | 'TROUBLESHOOTING_COMPLETE'
  | 'AWAITING_TERMS_ACCEPTANCE'
  | 'AUTHORIZED'
  | 'NEEDS_REVIEW'
  | 'DENIED'
  | 'LABEL_OPTIONS_PRESENTED'
  | 'LABEL_ISSUED'
  | 'AWAITING_CUSTOMER_SHIPMENT'
  | 'TRACKING_RECORDED'
  | 'CLOSED_FIXED';

